; One-byte semantic dispatcher with page-local trampolines to arbitrary handlers.

            %INCLUDE "memory-map.asmi"

            ORG CMPLRCRB
CMPLRCDS: ;@NUC-GLOBAL CompilerCodeStart PERMANENT CMPLRCDS
OFFSTTRM: ;@NUC-GLOBAL OffsetTrampolineSelectionStart PERMANENT OFFSTTRM
OFFSTTR0: ;@NUC-GLOBAL OffsetTrampolinePage PERMANENT OFFSTTR0
            DB OT0OFF
            DB OT1OFF
            DB OT2OFF
            DB OT3OFF
            DB OT4OFF
            DB OT5OFF
            DB OT6OFF
            DB OT7OFF
OFFSTTR1: JP DSPTCH0 ;@NUC-GLOBAL OffsetTrampoline0 PERMANENT OFFSTTR1
OFFSTTR2: JP DSPTCH1 ;@NUC-GLOBAL OffsetTrampoline1 PERMANENT OFFSTTR2
OFFSTTR3: JP DSPTCH2 ;@NUC-GLOBAL OffsetTrampoline2 PERMANENT OFFSTTR3
OFFSTTR4: JP DSPTCH3 ;@NUC-GLOBAL OffsetTrampoline3 PERMANENT OFFSTTR4
OFFSTTR5: JP DSPTCH4 ;@NUC-GLOBAL OffsetTrampoline4 PERMANENT OFFSTTR5
OFFSTTR6: JP DSPTCH5 ;@NUC-GLOBAL OffsetTrampoline5 PERMANENT OFFSTTR6
OFFSTTR7: JP DSPTCH6 ;@NUC-GLOBAL OffsetTrampoline6 PERMANENT OFFSTTR7
OFFSTTR8: JP DSPTCH7 ;@NUC-GLOBAL OffsetTrampoline7 PERMANENT OFFSTTR8
;@ROUTINE IN A OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A,HL
.L00000:
            SUB  12
            CP   8
            JR   NC,.L00001
            LD   L,A
            LD   H,0
            LD   L,(HL)
            LD   H,0
            JP   (HL)
.L00001:
            SCF
            RET
OFFSTTR9: ;@NUC-GLOBAL OffsetTrampolineSelectionEnd PERMANENT OFFSTTR9

;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH0:  OR A ;@NUC-GLOBAL Dispatch0 PERMANENT DSPTCH0
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH1:  OR A ;@NUC-GLOBAL Dispatch1 PERMANENT DSPTCH1
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH2:  OR A ;@NUC-GLOBAL Dispatch2 PERMANENT DSPTCH2
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH3:  OR A ;@NUC-GLOBAL Dispatch3 PERMANENT DSPTCH3
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH4:  OR A ;@NUC-GLOBAL Dispatch4 PERMANENT DSPTCH4
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH5:  OR A ;@NUC-GLOBAL Dispatch5 PERMANENT DSPTCH5
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH6:  OR A ;@NUC-GLOBAL Dispatch6 PERMANENT DSPTCH6
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH7:  OR A ;@NUC-GLOBAL Dispatch7 PERMANENT DSPTCH7
            RET
OT0OFF EQU OFFSTTR1-OFFSTTR0 ; trampoline dispatcher page offset 0
OT1OFF EQU OFFSTTR2-OFFSTTR0 ; trampoline dispatcher page offset 1
OT2OFF EQU OFFSTTR3-OFFSTTR0 ; trampoline dispatcher page offset 2
OT3OFF EQU OFFSTTR4-OFFSTTR0 ; trampoline dispatcher page offset 3
OT4OFF EQU OFFSTTR5-OFFSTTR0 ; trampoline dispatcher page offset 4
OT5OFF EQU OFFSTTR6-OFFSTTR0 ; trampoline dispatcher page offset 5
OT6OFF EQU OFFSTTR7-OFFSTTR0 ; trampoline dispatcher page offset 6
OT7OFF EQU OFFSTTR8-OFFSTTR0 ; trampoline dispatcher page offset 7
CMPLRCDE: ;@NUC-GLOBAL CompilerCodeEnd PERMANENT CMPLRCDE
CMPLRCRE: ;@NUC-GLOBAL CompilerCoreEnd PERMANENT CMPLRCRE

            ORG PRFBS
PRFSTRT: ;@NUC-GLOBAL ProofStart PERMANENT PRFSTRT
            LD   A,$A5
            LD   (PRFSTTS),A
            HALT
PRFSTTS: DB 0 ;@NUC-GLOBAL ProofStatus PERMANENT PRFSTTS
ProofEnd:

            ;@AZM-END
