; Isolated byte census for two equivalent eight-operation dispatch selectors.

            %INCLUDE "memory-map.asmi"

            ORG CMPLRCRB
CMPLRCDS: ;@NUC-GLOBAL CompilerCodeStart PERMANENT CMPLRCDS
TBLDSPTC: ;@NUC-GLOBAL TableDispatchStart PERMANENT TBLDSPTC
;@ROUTINE IN A OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A,DE,HL
.L00000:
            SUB  12
            CP   8
            JR   NC,.L00001
            ADD  A,A
            LD   E,A
            LD   D,0
            LD   HL,.L00002
            ADD  HL,DE
            LD   E,(HL)
            INC  HL
            LD   D,(HL)
            EX   DE,HL
            JP   (HL)
.L00001:
            SCF
            RET
.L00002:
            DW DSPTCH0,DSPTCH1,DSPTCH2,DSPTCH3
            DW DSPTCH4,DSPTCH5,DSPTCH6,DSPTCH7
TBLDSPT0: ;@NUC-GLOBAL TableDispatchEnd PERMANENT TBLDSPT0

CHNDSPTC: ;@NUC-GLOBAL ChainDispatchStart PERMANENT CHNDSPTC
;@ROUTINE IN A OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
.L00000:
            CP   12
            JP   Z,DSPTCH0
            CP   13
            JP   Z,DSPTCH1
            CP   14
            JP   Z,DSPTCH2
            CP   15
            JP   Z,DSPTCH3
            CP   16
            JP   Z,DSPTCH4
            CP   17
            JP   Z,DSPTCH5
            CP   18
            JP   Z,DSPTCH6
            CP   19
            JP   Z,DSPTCH7
            SCF
            RET
CHNDSPT0: ;@NUC-GLOBAL ChainDispatchEnd PERMANENT CHNDSPT0

;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH0:  OR A ;@NUC-GLOBAL Dispatch0 PERMANENT DSPTCH0
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH1:  OR A ;@NUC-GLOBAL Dispatch1 PERMANENT DSPTCH1
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH2:  OR A ;@NUC-GLOBAL Dispatch2 PERMANENT DSPTCH2
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH3:  OR A ;@NUC-GLOBAL Dispatch3 PERMANENT DSPTCH3
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH4:  OR A ;@NUC-GLOBAL Dispatch4 PERMANENT DSPTCH4
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH5:  OR A ;@NUC-GLOBAL Dispatch5 PERMANENT DSPTCH5
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH6:  OR A ;@NUC-GLOBAL Dispatch6 PERMANENT DSPTCH6
            RET
;@ROUTINE OUT CARRY,ZERO CLOBBERS SIGN,PARITY,HALFCARRY,A
DSPTCH7:  OR A ;@NUC-GLOBAL Dispatch7 PERMANENT DSPTCH7
            RET
CMPLRCDE: ;@NUC-GLOBAL CompilerCodeEnd PERMANENT CMPLRCDE
CMPLRCRE: ;@NUC-GLOBAL CompilerCoreEnd PERMANENT CMPLRCRE

            ORG PRFBS
PRFSTRT: ;@NUC-GLOBAL ProofStart PERMANENT PRFSTRT
            LD   A,$A5
            LD   (PRFSTTS),A
            HALT
PRFSTTS: DB 0 ;@NUC-GLOBAL ProofStatus PERMANENT PRFSTTS
ProofEnd:

            ;@AZM-END
