// Generated by scripts/generate-rewrite-actions.mjs. Do not edit.

export interface RewriteActionInstruction {
  readonly id: number;
  readonly name: string;
  readonly operands: readonly string[];
  readonly width: number;
}

export const rewriteActionInstructions: readonly RewriteActionInstruction[] = [
  {
    "name": "End",
    "operands": [],
    "id": 0,
    "width": 1
  },
  {
    "name": "Expect",
    "operands": [
      "token",
      "diagnostic"
    ],
    "id": 1,
    "width": 3
  },
  {
    "name": "Escape",
    "operands": [
      "selector"
    ],
    "id": 2,
    "width": 2
  },
  {
    "name": "Raise",
    "operands": [
      "diagnostic"
    ],
    "id": 3,
    "width": 2
  }
];
export const rewriteActionEscapes = [
  {
    "name": "ResetInitializer",
    "target": "RewriteInitializerReset",
    "id": 0
  }
] as const;

export const decodeRewriteActionProgram = (bytes: Uint8Array): readonly number[] => {
  const starts: number[] = [];
  let cursor = 0;
  while (cursor < bytes.length) {
    const start = cursor;
    const instruction = rewriteActionInstructions[bytes[cursor] ?? -1];
    if (instruction === undefined || cursor + instruction.width > bytes.length) {
      throw new Error(`invalid rewrite action at byte ${cursor}`);
    }
    if (instruction.name === "Escape" && (bytes[cursor + 1] ?? 256) >= rewriteActionEscapes.length) {
      throw new Error(`invalid rewrite action escape at byte ${cursor + 1}`);
    }
    starts.push(start);
    cursor += instruction.width;
    if (instruction.id === 0) {
      if (cursor !== bytes.length) throw new Error(`trailing rewrite action bytes at ${cursor}`);
      return starts;
    }
  }
  throw new Error("rewrite action program has no End");
};
