; Native ATOM composition of the unchanged call compiler proof.
; Immutable profile flags are supplied by native-slice-proof-profiles.mjs.
%INCLUDE "memory-map.asmi"
%INCLUDE "loop-compiler-state.asmi"
%INCLUDE "loop-z80-state.asmi"
%INCLUDE "nucleus-runtime-identity.asmi"
%INCLUDE "compiler-core-origin.asmi"
%INCLUDE "compiler-source-boundary.asmi"
%INCLUDE "source-adapter.asm"
%INCLUDE "compiler-tokenizer-boundary.asmi"
%INCLUDE "loop-tokenizer.asm"
%INCLUDE "compiler-semantic-boundary.asmi"
%INCLUDE "loop-semantic-sink.asm"
%INCLUDE "compiler-symbol-boundary.asmi"
%INCLUDE "loop-symbols.asm"
%INCLUDE "compiler-parser-boundary.asmi"
%INCLUDE "loop-parser.asm"
%INCLUDE "compiler-sink-boundary.asmi"
%INCLUDE "loop-z80-sink.asm"
%INCLUDE "slice-proof-immutable.asmi"
%INCLUDE "loop-keywords.asmi"
%INCLUDE "slice-proof-core-end.asmi"
%INCLUDE "call-slice-proof-sources.asm"
%INCLUDE "slice-proof-runtime-layout.asmi"
%INCLUDE "proof-z80-runtime.asm"
%INCLUDE "call-slice-proof-driver.asm"
