; Compile and execute the counted-loop source as direct Z80 code.

            .include "loop-z80-slice-proof-config.asmi"
            .include "memory-map.asmi"
            .include "proof-unsegmented-state.asmi"
            .include "loop-compiler-state.asmi"
            .include "loop-z80-state.asmi"

            .include "loop-z80-slice-code-begin.asmi"
            .include "source-adapter.asm"
            .include "loop-z80-slice-after-source-adapter.asmi"
            .include "loop-tokenizer.asm"
            .include "loop-z80-slice-after-tokenizer.asmi"
            .include "loop-semantic-sink.asm"
            .include "loop-z80-slice-after-semantic-sink.asmi"
            .include "loop-symbols.asm"
            .include "loop-z80-slice-after-symbols.asmi"
            .include "loop-parser.asm"
            .include "loop-z80-slice-after-parser.asmi"
            .include "loop-z80-sink.asm"
            .include "loop-z80-slice-after-loop-z80-sink.asmi"
            .include "loop-keywords.asmi"
            .include "loop-z80-slice-after-keywords.asmi"
            .include "loop-z80-slice-source.asmi"
            .include "loop-z80-slice-runtime-begin.asmi"
            .include "proof-z80-runtime.asm"
            .include "loop-z80-slice-runtime-after.asmi"
            .include "loop-z80-slice-proof-body.asmi"
            .include "loop-z80-slice-end.asmi"
