; Source proof for the u8-local and counted-loop compiler slice.

            .include "loop-compiler-slice-proof-config.asmi"
            .include "memory-map.asmi"
            .include "proof-unsegmented-state.asmi"
            .include "loop-compiler-state.asmi"

            .include "loop-compiler-slice-code-begin.asmi"
            .include "source-adapter.asm"
            .include "loop-compiler-slice-after-source-adapter.asmi"
            .include "loop-tokenizer.asm"
            .include "loop-compiler-slice-after-tokenizer.asmi"
            .include "loop-semantic-sink.asm"
            .include "loop-compiler-slice-after-semantic-sink.asmi"
            .include "loop-symbols.asm"
            .include "loop-compiler-slice-after-symbols.asmi"
            .include "loop-parser.asm"
            .include "loop-compiler-slice-after-parser.asmi"
            .include "loop-keywords.asmi"
            .include "loop-compiler-slice-after-keywords.asmi"
            .include "loop-compiler-slice-source.asmi"
            .include "loop-compiler-slice-proof-body.asmi"
            .include "loop-compiler-slice-end.asmi"
