; Compile and execute the exact Chapter 21 conformance corpus through the
; production packed LL(1) compiler and direct-Z80 backend.

            .include "stage9-conformance-z80-slice-proof-config.asmi"
            .include "memory-map.asmi"
            .include "proof-segmented-state.asmi"
            .include "loop-compiler-state.asmi"
            .include "aggregate-call-state.asmi"
            .include "loop-z80-state.asmi"

            .include "stage9-conformance-code-begin.asmi"
            .include "source-adapter.asm"
            .include "stage9-conformance-after-source-adapter.asmi"
            .include "loop-tokenizer.asm"
            .include "stage9-conformance-after-tokenizer.asmi"
            .include "loop-semantic-sink.asm"
            .include "stage9-conformance-after-semantic-sink.asmi"
            .include "loop-symbols.asm"
            .include "stage9-conformance-after-symbols.asmi"
            .include "loop-parser.asm"
            .include "stage9-conformance-after-parser.asmi"
            .include "loop-z80-sink.asm"
            .include "stage9-conformance-after-loop-z80-sink.asmi"
            .include "typed-expression-z80.asm"
            .include "stage9-conformance-after-typed-expression-z80.asmi"
            .include "aggregate-z80.asm"
            .include "stage9-conformance-after-aggregate-z80.asmi"
            .include "loop-keywords.asmi"
            .include "stage9-conformance-after-keywords.asmi"
            .include "stage9-conformance-runtime-begin.asmi"
            .include "proof-z80-runtime.asm"
            .include "stage9-conformance-runtime-after.asmi"
            .include "stage9-conformance-corpus-source.asmi"
            .include "stage9-conformance-proof-body.asmi"
