; Prove failable signatures and explicit failure on the packed LL(1) path.

            .include "stage8-failure-z80-slice-proof-config.asmi"
            .include "memory-map.asmi"
            .include "proof-segmented-state.asmi"
            .include "loop-compiler-state.asmi"
            .include "aggregate-call-state.asmi"
            .include "loop-z80-state.asmi"

            .include "stage8-failure-code-begin.asmi"
            .include "source-adapter.asm"
            .include "stage8-failure-after-source-adapter.asmi"
            .include "loop-tokenizer.asm"
            .include "stage8-failure-after-tokenizer.asmi"
            .include "loop-semantic-sink.asm"
            .include "stage8-failure-after-semantic-sink.asmi"
            .include "loop-symbols.asm"
            .include "stage8-failure-after-symbols.asmi"
            .include "loop-parser.asm"
            .include "stage8-failure-after-parser.asmi"
            .include "loop-z80-sink.asm"
            .include "stage8-failure-after-loop-z80-sink.asmi"
            .include "typed-expression-z80.asm"
            .include "stage8-failure-after-typed-expression-z80.asmi"
            .include "aggregate-z80.asm"
            .include "stage8-failure-after-aggregate-z80.asmi"
            .include "loop-keywords.asmi"
            .include "stage8-failure-after-keywords.asmi"
            .include "stage8-failure-source.asmi"
            .include "stage8-failure-spare-source.asmi"
            .include "stage8-failure-backup-source.asmi"
            .include "stage8-failure-runtime-begin.asmi"
            .include "proof-z80-runtime.asm"
            .include "stage8-failure-runtime-after.asmi"
            .include "stage8-failure-proof-body.asmi"
