; Compile and execute the first Nucleus source program as direct Z80 code.

            .include "z80-slice-proof-config.asmi"
            .include "memory-map.asmi"
            .include "compiler-state.asmi"
            .include "z80-state.asmi"

            .include "z80-slice-code-begin.asmi"
            .include "source-adapter.asm"
            .include "tokenizer.asm"
            .include "semantic-sink.asm"
            .include "parser.asm"
            .include "z80-slice-sink-begin.asmi"
            .include "z80-sink.asm"
            .include "z80-slice-after-sink.asmi"
            .include "z80-slice-source.asmi"
            .include "z80-slice-runtime-begin.asmi"
            .include "z80-runtime.asm"
            .include "z80-slice-proof-body.asmi"
            .include "z80-slice-end.asmi"
